image: ruby:2.6.0

cache:
  key: ruby:2.6.0
  paths:
    - vendor/ruby

rspec:
  stage: test
  script:
    - gem update --system
    - gem install bundler:2.1.4
    - bundle config set path 'vendor/ruby'
    - bundle install
    - bundle exec rspec spec
  artifacts:
    paths:
      - coverage/
  except:
      - tags

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
  except:
      - tags
