AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/ClassLength:
  Exclude:
    - 'lib/bbservices/service.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/bbservices/service_provider.rb'
Metrics/BlockLength:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false